### PR TITLE
Convert to maven project

### PR DESCRIPTION
**Pull request by lambdaupb**
- Generate jar-with-dependencies
 - Java version 1.8

Use java.util.Base64 to implement
 doc.DocReader.readServerDoc
instead of deprecated com.sun API

TODO: test Applet usage

### CODE REVIEW

**Comment by jaltekruse** [comment]
Thanks for the pull request! I've been meaning to set up a real build system. I'm just about to push a branch with your commit and just a gitignore change to add the maven target directory.

**Comment by ivanistheone** [comment]
Good stuff.

Is there another option to `java.util.Base64`, which seems to be only in Java 8. 

I have only Java 7 on my computer and I managed to build `lambdaupb:master` on Java 7 by changing:

                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>

and putting back in place the old `Base64` code.

**Comment by jaltekruse** [comment]
I didn't notice that, I do want to keep the codebase compatible with 1.7. Especially because there is a good chance that schools aren't up to date. I'll post a commit that will compile with 1.7.

**Comment by jaltekruse** [comment]
Hey @lambdaupb I noticed the contributor count didn't go up when I merged your change. It looks like the git install when you committed this does not have the e-mail associated with your github configured. I'd rather not do a force push to fix the existing commit, but I could if you would like me to give you credit associated with your GH account.

**Pull request merged**
